### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Heliozoa** [basic-ohjelmoia/dungeonette#2]
ladattu 31.8. 01:09

Mielenkiintoinen projekti, koodiin on selvästi käytetty paljon aikaa ja vaivaa. Jar:illa oli hauska generoida eri luolastoja. Sain myös koodin ajettua ja testattua ongelmitta. Ohjelma on melko monimutkainen joten en toiminnan osalta varmaankaan saa mitään tarkkaa palautetta annettua.
#### Dokumentaatio

Dokumentaatio selittää hyvin algoritmin perusidean, mikä on avuksi sen lukemiseen. Myös itse luokat ja metodit on hyvin kommentoituja jolloin ei ole tarpeen yrittää selvittää rivi kerrallaan, mitä koodi tekee.
#### Rakenne

Luokkarakenne on selkeä. Suurimmat ongelmat onkin jo osaksi huomioitu kommenteissa, esim. hyvin pitkä generateFloor-metodi. Samoin PassageCarverin processAllRoutes on pitkä, ja sisältää myös pitkiä rivejä joiden toiminta ei ole heti selkeää. Ohjelmaa selkeyttäisi paljon tiettyjen osien siirtäminen omiin privaatteihin metodeihin. Metodi antaisi myös nimen sille, mitä rivit tekevät ja edelleen helpottaisi koodin lukemista.
#### Koodi

Itse koodi vaikuttaa asianmukaisesti kirjoitetulta. Jo mainittuja pitkiä rivejä lukuunottamatta en huomannut mitään valittamista tai epäilyttävää. Voi olla että se sekoittaisi koodia, mutta ehkä itse kokeilisin eri merkkien kokoamista johonkin luokkaan, jolloin koodissa käytettäisiin wallTile (tai WALL_TILE?) muuttujia tjsp. itse merkin sijaan.
#### Testit

Itse tykkään pistää virhe-ilmoituksia (esim. assertTrue("taulukko oli liian pieni", taulukko.length < 10)) jotka muistuttavat ennen kaikkea myöhemmin, mitä olinkaan testaamassa. Selkeyttää myös virhetilanteita, kun näen heti tarkalleen mikä meni pieleen.

Onnea työn loppusuoralle! Ohjelma vaikuttaa olevan jo hyvässä vaiheessa.

**Comment by basic-ohjelmoia** [comment]
Kiitos palautteesta! Onnea myös omaan projektiisi!
- Tuomas
